# Generated by Django 5.1.6 on 2025-03-03 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historymodel',
            options={'verbose_name': 'история', 'verbose_name_plural': 'истории'},
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.historymodel', verbose_name='история'),
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название истории'),
        ),
    ]
